# Generated by Django 5.2.6 on 2025-09-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for this content', max_length=50),
        ),
        migrations.AddField(
            model_name='blogs',
            name='og_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogs',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='og_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogs',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary', max_length=20),
        ),
        migrations.AddField(
            model_name='blogs',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
