# Generated by Django 5.2.6 on 2025-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_canonical_url_blogs_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='canonical_url',
        ),
        migrations.AddField(
            model_name='blogs',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Post'), ('NewsArticle', 'News Article'), ('TechArticle', 'Technical Article')], default='Article', help_text='Schema.org type for structured data', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social media', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social media sharing (1200×630px recommended)', null=True, upload_to='og_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=90),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Type of Twitter Card to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='twitter_site',
            field=models.CharField(blank=True, help_text='Twitter @username of the site (without @)', max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
