# Generated by Django 5.2.6 on 2025-09-19 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_options_remove_blogs_canonical_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=5000, verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for this content', max_length=50, verbose_name='Focus Keyword'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social media', max_length=300, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social media sharing (1200×630px recommended)', null=True, upload_to='og_images/%Y/%m/%d/', verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=90, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Post'), ('NewsArticle', 'News Article'), ('TechArticle', 'Technical Article')], default='BlogPosting', help_text='Schema.org type for structured data', max_length=50, verbose_name='Schema Type'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='short_description',
            field=models.TextField(max_length=1000, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Type of Twitter Card to use', max_length=20, verbose_name='Twitter Card Type'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='twitter_site',
            field=models.CharField(blank=True, help_text='Twitter @username of the site (without @)', max_length=15, verbose_name='Twitter Site'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='blogs_categ_categor_25ee3c_idx'),
        ),
    ]
