# Generated by Django 5.2.6 on 2025-09-28 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish', 'Can publish blog post'), ('can_feature', 'Can feature blog post')], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'permissions': [('can_publish', 'Can publish post'), ('can_feature', 'Can feature post')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='blogs',
            name='blogs_blogs_status_ac3b46_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogs',
            name='blogs_blogs_created_b35545_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogs',
            name='blogs_blogs_slug_e96991_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogs',
            name='blogs_blogs_categor_30ece1_idx',
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['status', 'is_featured', 'created_at'], name='blogs_blogs_status_56a6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['slug', 'status'], name='blogs_blogs_slug_88d1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['category', 'status', 'created_at'], name='blogs_blogs_categor_475be6_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
