# Generated by Django 5.2.6 on 2025-09-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_comment_alter_blogs_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this ad', max_length=100)),
                ('ad_type', models.CharField(choices=[('GOOGLE_ADSENSE', 'Google AdSense'), ('AFFILIATE', 'Affiliate Ad'), ('CUSTOM', 'Custom Code'), ('BANNER', 'Image Banner')], default='CUSTOM', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ad is Active')),
                ('placement_area', models.CharField(choices=[('HEADER', 'Header'), ('SIDEBAR_TOP', 'Sidebar Top'), ('SIDEBAR_BOTTOM', 'Sidebar Bottom'), ('CONTENT_TOP', 'Content Top'), ('CONTENT_MIDDLE', 'Content Middle'), ('CONTENT_BOTTOM', 'Content Bottom'), ('FOOTER', 'Footer')], default='SIDEBAR_TOP', max_length=20)),
                ('ad_code', models.TextField(blank=True, help_text='Paste your Google AdSense code, affiliate script, or custom HTML/JavaScript here')),
                ('image', models.ImageField(blank=True, help_text='For image banner ads', null=True, upload_to='ads/')),
                ('destination_url', models.URLField(blank=True, help_text='For affiliate or image banner ads')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for image ads', max_length=200)),
                ('priority', models.IntegerField(default=1, help_text='Higher number means higher priority (1-10)')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
