# Generated by Django 5.2.6 on 2025-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_contactsubmission_legalpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteForUsSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('writing_category', models.CharField(choices=[('TECH', 'Technology'), ('BUSINESS', 'Business'), ('LIFESTYLE', 'Lifestyle'), ('HEALTH', 'Health & Wellness'), ('TRAVEL', 'Travel'), ('FOOD', 'Food & Cooking'), ('OTHER', 'Other')], default='TECH', max_length=20)),
                ('topic', models.CharField(help_text='What topic would you like to write about?', max_length=200)),
                ('writing_experience', models.TextField(blank=True, help_text='Briefly describe your writing experience')),
                ('portfolio_link', models.URLField(blank=True, help_text='Link to your portfolio or writing samples (optional)')),
                ('message', models.TextField(help_text='Tell us about your article idea')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='contact_type',
            field=models.CharField(choices=[('BUSINESS', 'Business Inquiry'), ('GENERAL', 'General Question'), ('TECHNICAL', 'Technical Support'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(choices=[('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms of Service'), ('COOKIE', 'Cookie Policy'), ('DISCLAIMER', 'Disclaimer'), ('ABOUT', 'About Us')], max_length=20, unique=True),
        ),
    ]
