# Generated by Django 5.2.7 on 2025-10-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_writeforussubmission_contactsubmission_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the default canonical URL', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='language',
            field=models.CharField(default='en', help_text='Language code (e.g. en, ar, fr)', max_length=10),
        ),
        migrations.AddField(
            model_name='blogs',
            name='parent_blog',
            field=models.ForeignKey(blank=True, help_text='Link to original post for translations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='blogs.blogs'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_code',
            field=models.TextField(blank=True, help_text='Paste AdSense or custom HTML code'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='destination_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ad Active'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='priority',
            field=models.IntegerField(default=1, help_text='Higher number = higher priority'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=10000, verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blogs.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for SEO', max_length=50, verbose_name='Focus Keyword'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200×630px recommended', null=True, upload_to='og_images/%Y/%m/%d/', verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='og_title',
            field=models.CharField(blank=True, max_length=90, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Post'), ('NewsArticle', 'News Article'), ('TechArticle', 'Technical Article')], default='BlogPosting', max_length=50, verbose_name='Schema Type'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=20, verbose_name='Twitter Card Type'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='twitter_site',
            field=models.CharField(blank=True, help_text='Twitter username without @', max_length=15, verbose_name='Twitter Site'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='writeforussubmission',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='writeforussubmission',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='writeforussubmission',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='writeforussubmission',
            name='writing_experience',
            field=models.TextField(blank=True),
        ),
    ]
