# Generated by Django 5.2.7 on 2025-10-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blogs_canonical_url_blogs_language_blogs_parent_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='display_strategy',
            field=models.CharField(choices=[('RANDOM', 'Random Rotation'), ('WEIGHTED', 'Weighted by Priority'), ('SEQUENTIAL', 'Sequential Display'), ('CATEGORY_MATCH', 'Match Post Category')], default='RANDOM', help_text='How this ad should be selected for display', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_display_count',
            field=models.PositiveIntegerField(default=0, help_text='Maximum times to display this ad (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_categories',
            field=models.ManyToManyField(blank=True, help_text='Only show this ad for posts in these categories (leave empty for all categories)', to='blogs.category'),
        ),
    ]
