# Generated by Django 5.2.7 on 2025-10-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_contact_newslettersubscriber_writeforus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='WriteForUs',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='display_strategy',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='max_display_count',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_categories',
        ),
    ]
