# Generated by Django 5.2.7 on 2025-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_advertisement_display_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('GOOGLE_ADSENSE', 'Google AdSense'), ('AFFILIATE', 'Affiliate Ad'), ('CUSTOM', 'Custom Code'), ('BANNER', 'Image Banner'), ('VIDEO_IN_STREAM', 'Video In-Stream'), ('VIDEO_OUT_STREAM', 'Video Out-Stream'), ('BUMPER', 'Bumper Ad')], default='CUSTOM', max_length=20),
        ),
    ]
