# Generated by Django 5.2.7 on 2025-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_alter_advertisement_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='placement_area',
            field=models.CharField(choices=[('HEADER', 'Header'), ('SIDEBAR_TOP', 'Sidebar Top'), ('SIDEBAR_BOTTOM', 'Sidebar Bottom'), ('CONTENT_TOP', 'Content Top'), ('CONTENT_MIDDLE', 'Content Middle'), ('CONTENT_BOTTOM', 'Content Bottom'), ('CONTENT_VIDEO', 'Content Video'), ('FOOTER', 'Footer')], default='SIDEBAR_TOP', max_length=20),
        ),
    ]
