# Generated by Django 5.2.7 on 2025-10-14 19:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_advertisement_placement_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='Blog Content'),
        ),
    ]
